version: '3.8'

services:
  # 前端Nginx服务
  frontend:
    image: museum_exhibition_web:${APP_VERSION}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: frontend-nginx
    ports:
      - "8088:80"
    depends_on:
      - backend
    restart: always
    networks:
      - ruoyi-network

  # 后端Flask服务
  backend:
    image: museum_exhibition_app:${APP_VERSION}
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: backend-runtime
    ports:
      - "9080:9000"
    env_file:
      - ../ruoyi_admin/config/.env
    environment:
      - RUOYI_ENV=prod
    restart: always
    networks:
      - ruoyi-network

networks:
  ruoyi-network:
    driver: bridge
