version: '3.8'

services:
  # 前端Nginx服务
  frontend:
    image: museum_exhibition_web:0.0.1
    ports:
      - "8088:80"
    depends_on:
      - backend
    restart: always
    networks:
      - ruoyi-network

  # 后端Flask服务
  backend:
    image: museum_exhibition_app:0.0.1
    ports:
      - "9002:9000"
    environment:
      # - FLASK_ENV=production
      # - DATABASE_URL=mysql+pymysql://root:password@db:3306/ry-vue
      - REDIS_URL1=redis://redis:6379/0
    restart: always
    networks:
      - ruoyi-network

networks:
  ruoyi-network:
    driver: bridge
