version: '3.8'

services:
  # 前端Nginx服务
  frontend:
    image: museum_exhibition_web:0.0.1
    ports:
      - "8088:80"
    depends_on:
      - backend
    restart: always
    networks:
      - ruoyi-network

  # 后端Flask服务
  backend:
    image: museum_exhibition_app:0.0.1
    ports:
      - "9080:9000"
    environment:
      - FLASK_ENV=prod
    restart: always
    networks:
      - ruoyi-network

networks:
  ruoyi-network:
    driver: bridge
