flask:
  secret_key: 'your_secret_key'
  debug: false
  testing: true
  CORS_ORIGINS: '*'
  SQLALCHEMY_DATABASE_URI: "${DATABASE_URI}"
  SQLALCHEMY_TRACK_MODIFICATIONS: true
  SQLALCHEMY_ECHO: false
  SQLALCHEMY_POOL_SIZE: 5
  SQLALCHEMY_POOL_TIMEOUT: 10
  SQLALCHEMY_POOL_RECYCLE: 500
  REDIS_URL: "${REDIS_URL}"
  MINIO_ENDPOINT: "${MINIO_ENDPOINT}"
  MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
  MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
  MINIO_BUCKET: "${MINIO_BUCKET}"

aicrawl:
  qwen:
    api_key: "${QIANWEN_API_KEY}"
    base_url: "https://dashscope.aliyuncs.com/api/v1"
    model_name: "qwen3-max"
  chromium:
    ws_endpoint: "${WS_ENDPOINT}"

log:
  level: DEBUG
  filename: logs/ruoyi.log
  filesize: 100MB
  filenum: 10
  formatter:
    fmt: '%(asctime)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s'
