flask:
  secret_key: 'your_secret_key'
  debug: false
  testing: true
  CORS_ORIGINS: '*'
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:infini_rag_flow@127.0.0.1:5455/ry_vue_dev'
  SQLALCHEMY_TRACK_MODIFICATIONS: true
  SQLALCHEMY_ECHO: false
  SQLALCHEMY_POOL_SIZE: 5
  SQLALCHEMY_POOL_TIMEOUT: 10
  SQLALCHEMY_POOL_RECYCLE: 500
  REDIS_URL: "redis://:infini_rag_flow@127.0.0.1:6379/10"

aicrawl:
  chromium:
    # ws_endpoint: "ws://127.0.0.1:3000/"
    # ws_endpoint: "ws://127.0.0.1:3000/"
    ws_endpoint: "ws://127.0.0.1:3001/"

log:
  level: DEBUG
  filename: logs/ruoyi.log
  filesize: 100MB
  filenum: 10
  formatter:
    fmt: '%(asctime)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s'