ruoyi:
  name: 'museum_exhibition'
  version: '1.0.0'
  author: 'leeon'
  host: '0.0.0.0'
  port: 9000
  api:
    version: '/'
  env: 'dev'
  profile: '/tmp/ruoyi/upload'

token:
  header: 'Authorization'
  secret: 'abcdefghijklmnopqrstuvwxyz'
  expireTime: 30
