ruoyi:
  name: 'ruoyi-vue-flask'
  version: '1.0.0'
  author: 'shaw'
  host: 'localhost'
  port: 9000
  api:
    version: '/'
  env: 'dev'
  profile: 'G:/ruoyi/uploadPath'

token:
  header: 'Authorization'
  secret: 'abcdefghijklmnopqrstuvwxyz'
  expireTime: 30
